name: m360ict_flutter_task
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_svg: ^2.1.0
  fluttertoast: ^8.2.12
  loading_animation_widget: ^1.3.0
  flutter_screenutil: ^5.9.3
  logger: ^2.5.0
  cached_network_image: ^3.4.1
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  bcrypt: ^1.1.3
  shared_preferences: ^2.5.3
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/